### ISSUE TITLE
trouble with first line of "Quick-install instructions for a typical installation"

### ISSUE THREAD

**Issue by rogera47** [gambit/gambit#803] opened 2022-12-05 05:30 UTC
If I enter the line.:

git clone https://github.com/gambit/gambit.git

I get the response:

Cloning into 'gambit'...
fatal: unable to access 'https://github.com/gambit/gambit.git/': SSL certificate problem: Invalid certificate chain

(2014 MacBook Air running Mac OS X 10.9.5)

Any help or advice appreciated.

Thank you,

RP

**Comment by gambiteer** [comment] 2022-12-05 18:42
I'm sorry, I can't reproduce this on Mac OS X 12.6.1:
```
[MacBook-Pro:/tmp] lucier% git clone https://github.com/gambit/gambit.git
Cloning into 'gambit'...
remote: Enumerating objects: 33668, done.
remote: Counting objects: 100% (280/280), done.
remote: Compressing objects: 100% (138/138), done.
remote: Total 33668 (delta 155), reused 247 (delta 132), pack-reused 33388
Receiving objects: 100% (33668/33668), 118.80 MiB | 21.82 MiB/s, done.
Resolving deltas: 100% (25749/25749), done.
```

**Comment by rogera47** [comment] 2022-12-05 22:47
I just tried again using a new machine:

MacBook Air (M2, 2022)
Mac OS X 12.5.1

Something more complicated came up iinvolving X code tools. Right now I don't want to follow the suggested instructions.

Thank you gambiteer for your quick reply to my query.

RP

**Comment by gambiteer** [comment] 2022-12-05 23:01
Nice machine.  (I have a 14" MacBook Pro with M1 Max.)
These are my command-line tools:
```
[MacBook-Pro:~] lucier% pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 14.1.0.0.1.1666437224
```
I found the 14.0 versions buggy.

**Comment by rogera47** [comment] 2022-12-06 05:07
to Gambiteer:

I sm definitely not a Pro level programmer and that is why I am unable to make  use of the suggestions you made.

However, you did not write that Gambit Scheme will not run on these new (non-intel CPUs). That is good news for me.

Please do not put any more effort into helping me. You have already gone beyond the call of duty.

Again, thank you,

RP

**Comment by gambiteer** [comment] 2022-12-08 19:57
You seem to want no more follow-up on this issue, so I'm going to close it.
Feel free to reopen if you need to.

**Closed by gambiteer** 2022-12-08 19:57 UTC

**Comment by rogera47** [comment] 2022-12-08 21:35
to Gambieteer:

You read my intentions perfectly. I don't know my way around GitHub at all, so likely I did not do what able users of Github do.
