### ISSUE TITLE
Netbsd beta 10 requires -lutil to build properly

### ISSUE THREAD

**Issue by ober** [gambit/gambit#845] opened 2023-07-31 15:45 UTC
https://gist.github.com/ober/b9179779efd1b2f633e01795590ad05d

**Comment by ober** [comment] 2023-07-31 15:51
This is on x86_64 gambit 4.9.5.

**Comment by feeley** [comment] 2023-08-01 01:22
I suspect the issue is due to using an Autoconf version different from 2.69 . To avoid the regeneration of "configure", try to do a make from the release tar ball (the "configure" script in the release is up to date and does not need to be regenerated). You can probably also "git clone ...;touch configure;./configure ...".

Can you try that to see if it solves the issue? If you can, can you revert to autoconf 2.69 to see if that also solves the issue?

**Comment by feeley** [comment] 2023-08-12 12:36
@ober ping!

**Comment by feeley** [comment] 2023-08-18 14:23
@ober I'm closing because I'm fairly confident it is an issue with not using autoconf 2.69 (I don't have NetBSD to reproduce). If my above suggestion does not work then reopen the issue.

**Closed by feeley** 2023-08-18 14:23 UTC
