### ISSUE TITLE
"make test-modules" fails at _define-library

### ISSUE THREAD

**Issue by gambiteer** [gambit/gambit#816] opened 2023-03-10 04:25 UTC
I see
```
heine:~/programs/gambit/gambit> make -i test-modules
make[1]: Entering directory '/home/lucier/programs/gambit/gambit/lib'
make[2]: Entering directory '/home/lucier/programs/gambit/gambit/lib/_define-library'
*** testing _define-library
free(): invalid pointer
Aborted (core dumped)
make[2]: [../module-common.mk:185: test-modules-pre] Error 134 (ignored)
```
I don't see any other failures in "make test-modules"

**Comment by feeley** [comment] 2023-07-24 11:58
Can't reproduce and have successfully done `make test-modules` in various environment so am closing.

**Closed by feeley** 2023-07-24 11:58 UTC
