### ISSUE TITLE
Failing some "13-modules" tests in v4.9.4: Can't open file in ~~lib

### ISSUE THREAD

**Issue by wolneykien** [gambit/gambit#814] opened 2023-02-09 22:51 UTC
```
$ LD_LIBRARY_PATH=../lib:../gsi:../gsc: ../gsi/gsi -:tl,~~bin=../bin,~~lib=../lib,~~include=../include -f ./run-unit-tests.scm
[257|  0]  90% ##############.. 12.4s 13-modules/prim_boolean.scm
*** FAILED 13-modules/prim_boolean.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_boolean.scm"@3.1 -- Can't open file "/usr/lib64/gambit/prim/boolean#.scm"
...
```

The `prim_boolean.scm` failed and some other tests in v4.9.4 failed the same way. The same error happens when I run the single test file and _don't pass the `~~lib` argument_, i. e.:

```
$ LD_LIBRARY_PATH=../lib:../gsi:../gsc: ../gsi/gsi -:tl,~~bin=../bin,~~include=../include -f unit-tests/13-modules/prim_boolean.scm 
*** ERROR IN "unit-tests/13-modules/prim_boolean.scm"@3.1 -- Can't open file "/usr/lib64/gambit/prim/boolean#.scm"
```

However, it passes OK with `~~lib=../lib` in options as in the `./run-unit-tests.scm` command above:

```
$ LD_LIBRARY_PATH=../lib:../gsi:../gsc: ../gsi/gsi -:tl,~~bin=../bin,~~lib=../lib,~~include=../include -f unit-tests/13-modules/prim_boolean.scm 
$ echo $?
0
```

A brief reading of `run-unit-tests.scm` shows that it runs a nested `gsi` with its own set of options which doesn't include `~~lib=` (i. e. it doesn't inherit and pass further that option). However, I don't understand, why it works that way: is it by design or it's an error?

**Comment by wolneykien** [comment] 2023-02-10 23:13
For some reason, using `GAMBOPT=~~lib=../lib` helps to pass the tests. However, the manual sais that this option is ignored if the command line argument starts with `-:` and that's what I see in `run-unit-tests.scm`.

**Comment by gambiteer** [comment] 2023-02-11 18:15
Marc, how would we debug this issue, find out where Gambit is looking for module headers?
I sometimes find that tests are loading already-installed files instead of newly built ones, so the tests pass, but they would fail if there were no installed Gambit, or the tests were not run in the build directory.  (I'm talking about tests in general, not the unit tests.)

**Comment by sevan** [comment] 2023-07-31 18:26
This is the list of checks which fail because they're attempting to load files from the install destination when running 'make check'.

```
[260|  0]  89% ##############.. 647.5s 13-modules/prim_boolean.scm
*** FAILED 13-modules/prim_boolean.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_boolean.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/boolean#.scm"

[260|  1]  90% ##############.. 648.0s 13-modules/prim_box.scm
*** FAILED 13-modules/prim_box.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_box.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/box#.scm"

[260|  2]  90% ##############.. 648.6s 13-modules/prim_char.scm
*** FAILED 13-modules/prim_char.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_char.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/char#.scm"

[260|  3]  91% ##############.. 649.2s 13-modules/prim_exception.scm
*** FAILED 13-modules/prim_exception.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_exception.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/exception#.scm"

[260|  4]  91% ##############.. 649.8s 13-modules/prim_f32vector.scm
*** FAILED 13-modules/prim_f32vector.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_f32vector.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/f32vector#.scm"

[260|  5]  91% ##############.. 650.6s 13-modules/prim_f64vector.scm
*** FAILED 13-modules/prim_f64vector.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_f64vector.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/f64vector#.scm"

[260|  6]  92% ##############.. 651.1s 13-modules/prim_filesystem.scm
*** FAILED 13-modules/prim_filesystem.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_filesystem.scm"@10.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/filesystem#.scm"

[260|  7]  92% ##############.. 651.8s 13-modules/prim_fixnum.scm
*** FAILED 13-modules/prim_fixnum.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_fixnum.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/fixnum#.scm"

[260|  8]  92% ##############.. 652.6s 13-modules/prim_flonum.scm
*** FAILED 13-modules/prim_flonum.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_flonum.scm"@8.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/flonum#.scm"

[260|  9]  93% ##############.. 653.3s 13-modules/prim_keyword.scm
*** FAILED 13-modules/prim_keyword.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_keyword.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/keyword#.scm"

[260| 10]  93% ##############.. 653.9s 13-modules/prim_list.scm
*** FAILED 13-modules/prim_list.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_list.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/list#.scm"

[260| 11]  93% ###############. 654.7s 13-modules/prim_misc.scm
*** FAILED 13-modules/prim_misc.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_misc.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/misc#.scm"

[260| 12]  94% ###############. 655.4s 13-modules/prim_number.scm
*** FAILED 13-modules/prim_number.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_number.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/number#.scm"

[260| 13]  94% ###############. 656.5s 13-modules/prim_os.scm
*** FAILED 13-modules/prim_os.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_os.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/os#.scm"

[260| 14]  94% ###############. 657.0s 13-modules/prim_port.scm
*** FAILED 13-modules/prim_port.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_port.scm"@6.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/port#.scm"

[260| 15]  95% ###############. 658.5s 13-modules/prim_s16vector.scm
*** FAILED 13-modules/prim_s16vector.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_s16vector.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/s16vector#.scm"

[260| 16]  95% ###############. 659.1s 13-modules/prim_s32vector.scm
*** FAILED 13-modules/prim_s32vector.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_s32vector.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/s32vector#.scm"

[260| 17]  95% ###############. 659.7s 13-modules/prim_s64vector.scm
*** FAILED 13-modules/prim_s64vector.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_s64vector.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/s64vector#.scm"

[260| 18]  96% ###############. 660.3s 13-modules/prim_s8vector.scm
*** FAILED 13-modules/prim_s8vector.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_s8vector.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/s8vector#.scm"

[260| 19]  96% ###############. 660.9s 13-modules/prim_string.scm
*** FAILED 13-modules/prim_string.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_string.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/string#.scm"

[260| 20]  96% ###############. 661.7s 13-modules/prim_symbol.scm
*** FAILED 13-modules/prim_symbol.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_symbol.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/symbol#.scm"

[260| 21]  97% ###############. 662.2s 13-modules/prim_table.scm
*** FAILED 13-modules/prim_table.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_table.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/table#.scm"

[260| 22]  97% ###############. 662.8s 13-modules/prim_u16vector.scm
*** FAILED 13-modules/prim_u16vector.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_u16vector.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/u16vector#.scm"

[260| 23]  97% ###############. 663.3s 13-modules/prim_u32vector.scm
*** FAILED 13-modules/prim_u32vector.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_u32vector.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/u32vector#.scm"

[260| 24]  98% ###############. 663.9s 13-modules/prim_u64vector.scm
*** FAILED 13-modules/prim_u64vector.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_u64vector.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/u64vector#.scm"

[260| 25]  98% ###############. 664.5s 13-modules/prim_u8vector.scm
*** FAILED 13-modules/prim_u8vector.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_u8vector.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/u8vector#.scm"

[260| 26]  98% ###############. 665.1s 13-modules/prim_vector.scm
*** FAILED 13-modules/prim_vector.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_vector.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/vector#.scm"

[260| 27]  99% ###############. 665.7s 13-modules/prim_will.scm
*** FAILED 13-modules/prim_will.scm WITH EXIT CODE HI=70 LO=0
*** ERROR IN "unit-tests/13-modules/prim_will.scm"@3.1 -- Can't open file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/will#.scm"

[260| 28]  99% ###############. 666.3s 14-control/exceptions.scm
[261| 28] 100% ################ 667.7s
FAILED 28 UNIT TESTS OUT OF 289 (9.7%)
make[2]: *** [ut] Error 1
make[1]: *** [test11] Error 2
make: *** [check] Error 2
```

**Comment by feeley** [comment] 2023-08-01 01:11
Is this reproducible on v4.9.5 ?

To debug the module loading you can add the `-:d4` runtime option that will give a trace of the files that are searched and found. For example:

```
$ gsi -:d4 srfi/0/demo
*** (try-opening-source-file "/usr/local/Gambit/lib/srfi/0/demo/demo.sld")
*** (try-opening-source-file "/usr/local/Gambit/lib/srfi/0/demo/demo.scm")
*** (path-exists? "/usr/local/Gambit/lib/srfi/0/demo/demo@gambit409005@C/demo.o1")
*** (path-exists? "/usr/local/Gambit/lib/srfi/0/demo/demo.o1")
Using Gambit.
Demo source code:

#!/usr/bin/env gsi-script
;; Note: guile needs the script line to be balanced with: !#

;; Many Scheme implementations including Gambit have a builtin
;; definition of cond-expand, so (import (srfi 0)) is not needed.
;; This program can be run with various Scheme systems like this:
;;
;; $ gsi srfi/0/demo                           # Gambit
;; $ ./lib/srfi/0/demo/demo.scm                # Gambit
;; $ guile lib/srfi/0/demo/demo.scm            # Guile
;; $ csi -s lib/srfi/0/demo/demo.scm           # Chicken
;; $ chibi-scheme -q lib/srfi/0/demo/demo.scm  # Chibi

(cond-expand
  (gambit  (print "Using Gambit.\n")
           (define-cond-expand-feature foo)) ;; define foo feature
  (guile   (display "Using Guile.\n"))
  (chicken (display "Using Chicken.\n"))
  (else    (display "Using an unknown Scheme implementation.\n")))

(cond-expand
  (foo (print "Demo source code:\n\n" (read-file-string (this-source-file))))
  (else))
```

**Comment by sevan** [comment] 2023-08-01 02:14
> Is this reproducible on v4.9.5 ?

Yes, the output I posted is from v4.9.5

**Comment by feeley** [comment] 2023-08-01 10:35
I can't reproduce this issue locally. Did you build with special configure options? Can you give the output of `../gsi/gsi -v` and verify the presence of the file `/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/boolean#.scm` and the permissions on all parent directories?

**Comment by sevan** [comment] 2023-08-01 11:38
output of `gsi-gambit -v`
```
v4.9.5 20230726044844 powerpc-apple-darwin8.11.0 "./configure '--disable-debug' '--prefix=/Sandbox/tigerbrew/Cellar/gambit    -scheme/4.9.5' '--libdir=/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c' '--infodir=/Sandbox/tigerbrew/Cellar/    gambit-scheme/4.9.5/share/info' '--docdir=/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/share/doc/gambit-scheme' '--enable    -dynamic-clib' '--enable-compiler-name=gsc-gambit' '--enable-interpreter-name=gsi-gambit' '--enable-openssl' 'CC=/usr/bin/    gcc-4.0' 'CFLAGS=-w -pipe' 'LDFLAGS=-L/Sandbox/tigerbrew/opt/openssl/lib -L/Sandbox/tigerbrew/lib  -F/Sandbox/tigerbrew/Fr    ameworks -Wl,-headerpad_max_install_names' 'CPPFLAGS=-I/Sandbox/tigerbrew/opt/openssl/include -isystem/Sandbox/tigerbrew/i    nclude -F/Sandbox/tigerbrew/Frameworks' 'CXX=/usr/bin/g++-4.0' 'CXXFLAGS=-w -pipe'"
```
The file is there, this is an unprivileged build (built with my account rather than root) so there isn't any permisions there
```
% find Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim -name "boolean#.scm"
Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/boolean#.scm
```

However, `Sandbox` directory is symlinked into place from another partition so there is a difference between the actual path, I can try building and running the test suite from a location that isn't symlinked later tonight, if that'd help.

**Comment by sevan** [comment] 2023-08-15 01:31
Tried again from a subdirectory in my homedictory which is not symlinked into place.
Switched from Tiger PowerPC to Leopard i386, exact same thing happend with v4.9.5

**Comment by feeley** [comment] 2023-08-15 02:23
Can you start up `gsi` and then at the REPL try:

```
> (open-input-file "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/boolean#.scm")
```

and

```
> (file-info "/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c/gambit/prim/boolean#.scm")
```

**Comment by feeley** [comment] 2023-08-18 14:25
@sevan ping!

**Comment by sevan** [comment] 2023-08-18 15:04
@feeley Apologies Marc, I'll take a look and report back in a few hours.

**Comment by sevan** [comment] 2023-08-18 23:08
So running `./configure`, then `make check`, means that those paths are empty, and when I run `gsi/gsi` from the source directry, I get `*** ERROR IN (stdin)@1.1 -- No such file or directory`.
Am I meant to do `configure`, `make install`, `make check`?

**Comment by feeley** [comment] 2023-08-18 23:34
You do not need to `make install` to run `make check`. So this sequence is what you want to test:

```
./configure --enable-single-host
make clean
make core
make check
```

Please report if this works, and if not the complete trace.

**Comment by sevan** [comment] 2023-08-19 00:20
```
[289|  0] 100% ████████████████ 300.2s
PASSED ALL 289 UNIT TESTS
        ============ ALL TESTS SUCCESSFUL
```

That just works. I skipped `--enable-single-host` as that needs a more recent compiler and so just ran `./configure`.
This is what I was being tested with
```
./configure
--disable-debug
--prefix=/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5
--libdir=/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/lib/gambit-c
--infodir=/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/share/info
--docdir=/Sandbox/tigerbrew/Cellar/gambit-scheme/4.9.5/share/doc/gambit-scheme
--enable-dynamic-clib
--enable-compiler-name=gsc-gambit
--enable-interpreter-name=gsi-gambit
--enable-openssl
```

**Comment by feeley** [comment] 2023-08-19 00:25
So with those configure options the `make check` fails with the errors reported initially? If there are errors, could you try to `sudo make install` before you do the `make check`? This shouldn't be needed, but I'm curious if it solves the issue.

**Comment by sevan** [comment] 2023-08-19 00:34
Retesting now. As an aside, it would be useful if PR #846 was merged.

**Comment by sevan** [comment] 2023-08-19 01:17
Yep, since make install wasn't run initially, destdir was empty. Running `make install` populate it, obviously, and then the subsequent run of `make check` passes just fine.
So it looks like specifying --libdir & possibly --prefix trips up the make check stage (those paths should only be used for linking and install stage?).

As an aside, I've noticed that trying to use a specific version of make fails. When I was investigating this issue initially, I thought it might be fall out from the now ancient version of gnu make supplied with my vintage OS X. So I passed $MAKE=/path/to/new/make to configure, but I noticed that it uses the new make I stated initially, but it re-detects the OS supplied version and uses that for the build. To force the use of my stated version, I renamed the OS supplied versions, that broke the build.

**Comment by sevan** [comment] 2023-08-19 01:57
Just passing `--libdir` to `configure` is sufficient to recreate the issue, e.g
`./configure --libdir=/tmp/foo`

**Comment by feeley** [comment] 2023-08-19 19:39
Thanks! That last comment was helpful to find and solve the issue!

**Closed** 2023-08-19 19:38 UTC

**Comment by sevan** [comment] 2023-08-19 20:34
Thanks for the fix.
