### ISSUE TITLE
gsi opens new terminal window

### ISSUE THREAD

**Issue by bjornkihlberg** [gambit/gambit#749] opened 2022-04-26 03:37 UTC
gsi opens a new terminal window which means that I can't work interactively with the REPL by sending expressions from visual studio code to it. How do I prevent gsi from opening a new terminal window?

**Comment by feeley** [comment] 2022-04-26 13:12
Which version of Gambit are you using?  On Windows the REPL user interaction can be done on stdin/stdout or on the "Windows Console" and if the program doesn't yet have one allocated a fresh console is created (which is probably what you are experiencing).  Using the console is useful to debug programs that do I/O on stdin/stdout without interfering with those ports. The current version of Gambit defaults to using stdin/stdout (because most programmers expect this) but older versions default to using the console. The REPL interaction channel can be forced to use stdin/stdout with the `-:d-` command line option.  To force using the console there is the `-:dc` command line option.  There is also `-:d+` which is like `-:d-` but uses stderr for error messages.  You can download the latest version for Windows from: https://github.com/gambit/gambit/actions/runs/2157769059

**Comment by feeley** [comment] 2022-04-28 12:13
Can you confirm if this fixes your issue?

**Comment by bjornkihlberg** [comment] 2022-04-29 02:27
Nope, it doesn't work. Here are some screenshots:
![image](https://user-images.githubusercontent.com/38290734/165876002-3befea1e-9b92-4b91-a5bb-667c5bc7b096.png)
![image](https://user-images.githubusercontent.com/38290734/165876057-bff04a3b-5ba4-4e24-bfa2-6957f8b906fb.png)

Here's the workflow that I can do with ChezScheme for example since it doesn't start a new console:
![workflow](https://user-images.githubusercontent.com/38290734/165876535-2ac0339e-f0a4-45a6-9d7a-55f0e16523a8.gif)
*Note that I don't have to tab over to the console all the time. Just pressing **Alt+Enter** to send the code under the caret to the console is a very nice and fast workflow.*

**Comment by feeley** [comment] 2022-04-29 03:04
I see you are using a recent version of Gambit, which is good.  However, which build is it?  Using the MSCV or MINGW C compilers?  If you can try both to make sure the problem is not linked to th C compiler.

**Comment by bjornkihlberg** [comment] 2022-04-29 03:49
I tried all three that supports Windows
- **gambit-win-mingw-i686**
- **gambit-win-mingw-x86_64**
- **gambit-win-msvc-x86_64**

**Comment by feeley** [comment] 2022-04-29 03:57
OK. I'll take a closer look tomorrow.

**Comment by bjornkihlberg** [comment] 2022-04-29 03:59
No worries, thank you! Gambit seems very interesting. I'm working on VS code extensions for Scheme and the debugger in Gambit seems to be perfectly designed for integrating it directly into VS code

**Comment by feeley** [comment] 2022-04-29 18:15
This is now fixed by commit b262854449e69ce7acc0d9f239ef7341736bc150 .  I tested with the MSVC version that can be downloaded from https://github.com/gambit/gambit/actions/runs/2246486183 .  Please give it a try and reopen this issue if there is still a problem.

It turns out the problem is specific to VisualCode.  It uses a hidden "console" (the technical WIN32 term) for the gsi process but it also implements a redirection of the I/O to this console to show it in the VisualCode console.  To prevent interacting on a hidden WIN32 console the Gambit runtime system used to allocate a new one.  Now it simply uses the CONIN$/CONOUT$ "files" without creating a new WIN32 console.

I'm impressed with the VisualCode shell integration.  The Gambit REPL emacs-compatible keybindings appear to be usable inside VisualCode, for example ESC right-arrow to move the cursor forward by one s-expression, or ESC ctrl-t to transpose two s-expressions, and also ctrl-d to exit gsi.  Parenthesis matching and input highlighting seem to work too.  By the way, the `-:tE` runtime option turns off the Gambit line-editing features if they happen to interfere.

If you can find the time, it would be nice to write up a HOWTO explaining the use of Gambit inside VisualCode.  For example, I don't know how you configured Alt-Enter to send expressions to the interpreter.  I'm sure there are other useful tricks too.  This HOWTO could go in the manual in a section similar to the one for emacs.

**Closed by feeley** 2022-04-29 18:15 UTC
