### ISSUE TITLE
Installed files have odd permissions

### ISSUE THREAD

**Issue by FrictionlessMike** [gambit/gambit#426] opened 2019-11-05 06:35 UTC
This is on Linux, using commit 509d906265934db309f85fb0bd1a6dd7015c2322. After sudo make install I discovered this:
```
~ $ ls -l /usr/local/Gambit
total 6
drwxr-xr-x   1 root           root      792 2019-11-04 22:39 bin
drwx------   1 root           root       62 2019-11-04 22:39 doc
drwx------   1 root           root       52 2019-11-04 22:38 include
drwx------   1 root           root      100 2019-11-04 22:39 info
drwxr-xr-x   1 root           root     5234 2019-11-04 22:39 lib
drwxr-xr-x   1 root           root       16 2019-08-28 04:11 share
```

With ```include``` unreadable, I couldn't compile anymore:

```
~ $ gsc -exe square.scm
*** ERROR IN ##parameterize1 -- Permission denied
(current-directory "/usr/local/Gambit/include/")
```

Not sure how I could have caused this to happen.

```
sudo make uninstall
make distclean
./configure --enable-rtlib-debug-source --enable-single-host --enable-debug && \
make bootstrap && make bootclean && make doc && make -j5 && make modules \
&& sudo make -j5 install
```

On trying to reproduce it, I deleted /usr/local/Gambit, re-ran the configure->install procedure, and /usr/local/Gambit itself had ```drwx------``` permissions.

**Comment by FredericHamel** [comment] 2019-11-05 12:30
What are the permissions of `doc`, `include` and `info` before installing?

**Comment by FrictionlessMike** [comment] 2019-11-05 16:32
> What are the permissions of `doc`, `include` and `info` before installing?

The ones in the source tree are `drwxr-xr-x`

**Comment by feeley** [comment] 2019-11-05 17:01
On what variant of linux is this happening?  Perhaps it has some automatic security measures to prevent files created by root to be readable/executable.  Here are the relevant parts of the makefiles for installation:

```
INSTALL_DATA = $(rootfromhere)/install-sh -c -m 644
INSTALL_LIB = $(rootfromhere)/install-sh -c -m 644
INSTALL_PROGRAM = $(rootfromhere)/install-sh -c -m 755
```

As you can see it asks for the installed files to be created with permissions 644 or 755, so the OS is probably masking the permission bits.

**Comment by FrictionlessMike** [comment] 2019-11-06 01:50
I'm on Voidlinux.

```
$ cat /proc/version
Linux version 5.3.8_2 (void-buildslave@a-hel-fi) (gcc version 9.2.0 (GCC)) #1 SMP PREEMPT Fri Nov 1 01:39:56 UTC 2019
```

To my knowledge Voidlinux does nothing unusual in terms of security; this sort of thing doesn't normally happen when using the autotools/GCC toolchain. Not sure why it only happens in this project, but any files generated by ```sudo make``` will be ```-rw-------```, including anything generated in the source directory. It also somehow changes ownership and permissions on ```.git/index``` of all things.

I think I'll have to look at the makefile to determine the exact cause.

**Comment by feeley** [comment] 2019-11-06 02:06
Does `root` have a special umask?  What is the result of `sudo touch foo;ls -l foo`?

**Comment by FrictionlessMike** [comment] 2019-11-06 03:44
Apparently so:

```
$ sudo touch foo; ls -l foo
Password:
-rw------- 1 root root 0 Nov  5 19:19 foo
```

Voidlinux has had "umask" issues before, as it turns out, and now I'm having problems just in the last 24 hours, right after having to reinstall a bunch of packages. Probably not a coincidence.

**Comment by feeley** [comment] 2019-11-06 10:12
Given that the issue seems to be related to Voidlinux, I am closing this issue.  Please reopen it if you discover it really is Gambit specific.

**Closed by feeley** 2019-11-06 10:12 UTC

**Comment by FredericHamel** [comment] 2019-11-09 17:27
The issue is related to sudo. 
You need to add the following line to the sudo configuration file `/etc/sudoers`.
```
Defaults umask = 022
```
It will fix the umask of sudo command.

**Comment by gambiteer** [comment] 2019-11-09 17:31
Impressive diagnosis!
